# Generated by Django 5.1.3 on 2026-07-21 23:31

import apps.alerts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('severity_default', models.CharField(choices=[('CRITICAL', 'Critique'), ('MAJOR', 'Majeure'), ('MINOR', 'Mineure'), ('INFO', 'Information')], default='MAJOR', max_length=20)),
                ('color', models.CharField(blank=True, default='#f59e0b', max_length=20)),
                ('requires_maintenance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Catégorie d'alerte",
                'verbose_name_plural': "Catégories d'alertes",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('MAJOR', 'Majeure'), ('MINOR', 'Mineure'), ('INFO', 'Information')], default='MAJOR', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('ACKNOWLEDGED', 'Acquittée'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolue'), ('CLOSED', 'Clôturée')], default='OPEN', max_length=20)),
                ('worker_name', models.CharField(blank=True, default='', max_length=200)),
                ('shift', models.CharField(blank=True, default='', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('downtime_min', models.PositiveIntegerField(default=0)),
                ('bottles_lost', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.alerts.models._upload_to)),
                ('priority_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='machines.machine')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertcategory')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alerts.alert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Commentaire d'alerte",
                'verbose_name_plural': "Commentaires d'alertes",
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['machine', '-created_at'], name='alerts_aler_machine_cd30a1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx'),
        ),
    ]
