# Generated by Django 5.1.3 on 2026-07-21 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(help_text='Créneau horaire 1-24')),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Matin (06h-14h)'), ('AFTERNOON', 'Après-midi (14h-22h)'), ('NIGHT', 'Nuit (22h-06h)')], default='', max_length=20)),
                ('bottles_produced', models.PositiveIntegerField(default=0)),
                ('caps_produced', models.PositiveIntegerField(default=0)),
                ('reject_count', models.PositiveIntegerField(default=0)),
                ('reject_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('downtime_min', models.PositiveIntegerField(default=0)),
                ('downtime_reason', models.CharField(blank=True, default='', max_length=200)),
                ('pet_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('air_m3', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='machines.machine')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saisie production',
                'verbose_name_plural': 'Saisies production',
                'ordering': ['-date', '-hour', 'machine__code'],
                'indexes': [models.Index(fields=['date', 'hour'], name='production__date_dbcbe3_idx'), models.Index(fields=['machine', 'date'], name='production__machine_449849_idx')],
                'unique_together': {('date', 'hour', 'machine')},
            },
        ),
    ]
