# Generated by Django 5.1.3 on 2026-08-22 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_planningorder_options_and_more'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='colorant_consumed_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='planning_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to='planning.planningorder'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='raw_material_consumed_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('STOCK_CONSUMED', 'Stock consommé')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_production_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
