# Generated by Django 5.1.3 on 2026-08-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionentry_colorant_consumed_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionentry',
            name='air_m3',
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='energy_kwh',
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='pet_kg',
        ),
    ]
