# Generated by Django 5.1.3 on 2026-07-21 23:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de coût',
                'verbose_name_plural': 'Paramètres de coûts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(blank=True, default='', max_length=20)),
                ('pet_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('energy_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('air_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('production_count', models.PositiveIntegerField(default=0)),
                ('cost_per_bottle', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_records', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Enregistrement de coût',
                'verbose_name_plural': 'Enregistrements de coûts',
                'ordering': ['-date', 'machine__code'],
                'unique_together': {('date', 'shift', 'machine')},
            },
        ),
    ]
