# Generated by Django 5.1.3 on 2026-08-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costrecord',
            name='air_cost',
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='pet_cost',
        ),
    ]
