# Generated by Django 5.1.3 on 2026-07-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('machines', '0002_machine_manufacturer_machine_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_machines',
            field=models.ManyToManyField(blank=True, related_name='assigned_suppliers', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('CONTROLLER', 'Contrôleur'), ('MAINTENANCE', 'Maintenance'), ('OPERATOR', 'Opérateur'), ('SUPPLIER', 'Fournisseur')], default='CONTROLLER', max_length=20),
        ),
    ]
