# Generated by Django 5.1.3 on 2026-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_assigned_machines_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', "Chef d'équipe"), ('CONTROLLER', 'Contrôleur'), ('MAINTENANCE', 'Maintenance'), ('OPERATOR', 'Opérateur'), ('SUPPLIER', 'Fournisseur')], default='CONTROLLER', max_length=20),
        ),
    ]
