# Generated by Django 5.1.3 on 2026-08-18 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
        ('machines', '0004_parameter_text_value_alter_parameter_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('MORNING', 'Matin (06h-14h)'), ('AFTERNOON', 'Après-midi (14h-22h)'), ('NIGHT', 'Nuit (22h-06h)')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='machines.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation de shift',
                'verbose_name_plural': 'Affectations de shift',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['user', '-starts_at'], name='accounts_sh_user_id_7bb6f0_idx'), models.Index(fields=['machine', '-starts_at'], name='accounts_sh_machine_c51e9a_idx')],
            },
        ),
    ]
