# Generated by Django 5.1.3 on 2026-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('ISBM', 'Souffleuse ISBM'), ('INJECTION', 'Presse à injection'), ('COMPRESSOR', 'Compresseur'), ('CHILLER', 'Groupe eau froide')], default='ISBM', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'En marche'), ('STOPPED', 'Arrêtée'), ('MAINTENANCE', 'Maintenance'), ('BREAKDOWN', 'En panne')], default='STOPPED', max_length=20)),
                ('nominal_bph', models.PositiveIntegerField(default=0, help_text='Cadence nominale bouteilles/heure')),
                ('nominal_cph', models.PositiveIntegerField(default=0, help_text='Cadence nominale bouchons/heure')),
                ('cavities', models.PositiveIntegerField(default=6)),
                ('product_format', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, default='general', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['category', 'key'],
            },
        ),
    ]
