# Generated by Django 5.1.3 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_manufacturer_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'En marche'), ('STOPPED', 'Arrêtée'), ('MAINTENANCE', 'Maintenance'), ('BREAKDOWN', 'En panne')], default='RUNNING', max_length=20),
        ),
    ]
