# Generated by Django 5.1.3 on 2026-08-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='text_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
