# Generated by Django 5.1.3 on 2026-08-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_seed_steg_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machines', models.ManyToManyField(blank=True, related_name='auxiliary_equipment', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Équipement auxiliaire',
                'verbose_name_plural': 'Équipements auxiliaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Composant machine',
                'verbose_name_plural': 'Composants machine',
                'ordering': ['machine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mold', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Moule',
                'verbose_name_plural': 'Moules',
                'ordering': ['machine', 'id'],
            },
        ),
    ]
