# Generated by Django 5.1.3 on 2026-08-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_seed_machine_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('display', models.CharField(choices=[('GAUGE', 'Jauge (%)'), ('BAR', 'Barre + valeur')], default='BAR', max_length=10)),
                ('current_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('warning_tolerance_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='machines.machinecomponent')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='machines.machine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre machine',
                'verbose_name_plural': 'Paramètres machine',
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', True), ('machine__isnull', False)), models.Q(('component__isnull', False), ('machine__isnull', True)), _connector='OR'), name='machine_parameter_exactly_one_target')],
            },
        ),
    ]
