# Generated by Django 5.1.3 on 2026-08-19 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RAW_MATERIAL', 'Matière première'), ('COLORANT', 'Colorant')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=120)),
                ('ral', models.CharField(blank=True, default='', max_length=20)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('batch', models.CharField(blank=True, default='', max_length=60)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de stock',
                'verbose_name_plural': 'Articles de stock',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEIPT', 'Réception'), ('CONSUMPTION', 'Consommation'), ('ADJUSTMENT', 'Ajustement')], max_length=20)),
                ('delta', models.DecimalField(decimal_places=3, help_text='Positif = ajout, négatif = retrait', max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['created_at'],
            },
        ),
    ]
