# Generated by Django 5.1.3 on 2026-08-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningorder'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='planning.planningorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Réservation de stock',
                'verbose_name_plural': 'Réservations de stock',
                'ordering': ['stock_item', 'planning_order'],
                'unique_together': {('planning_order', 'stock_item', 'component_type')},
            },
        ),
    ]
