# Generated by Django 5.1.3 on 2026-08-22 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_type',
            field=models.CharField(blank=True, choices=[('PLANNING_ORDER', 'Commande de planning'), ('PACKAGE', 'Sac (sans commande)')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type__gt', ''), ('source_id__isnull', False)), fields=('source_type', 'source_id', 'stock_item', 'type'), name='unique_stock_movement_per_source'),
        ),
    ]
