"""Tests for /api/v1/alerts CRUD (POST declare, GET list, GET retrieve, DELETE).

Permission layout (apps/alerts/views.py):
- AlertViewSet.permission_classes = (IsAuthenticated,)        [viewset-level]
- perform_create blocks non-authorized roles inline:
    allowed_roles = ADMIN, MANAGER, CONTROLLER, MAINTENANCE   [views.py:53]
  (OPERATOR is rejected); no on-duty enforcement at the moment
  (the if-block at views.py:55 ends with `pass` — see test_offduty_*).
- destroy has NO explicit decorator -> falls back to viewset permission only
  (= IsAuthenticated). So ANY authenticated role may currently DELETE any alert.
  This is bug #5 — captured with @pytest.mark.xfail.
"""
import pytest

from apps.alerts.models import Alert, AlertStatus, Severity

pytestmark = pytest.mark.django_db

ALERTS_URL = "/api/v1/alerts"


def _declare_payload(machine, category, severity="MAJOR", worker="T. Operator"):
    return {
        "machine": machine.pk,
        "category": category.pk,
        "title": "Test alert",
        "description": "auto-generated by tests",
        "severity": severity,
        "worker_name": worker,
        "shift": "MORNING",
        "downtime_min": 5,
        "bottles_lost": 10,
    }


# ---------------------------------------------------------------------------
# List / retrieve — every authenticated role
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("role", ["ADMIN", "MANAGER", "CONTROLLER", "MAINTENANCE", "OPERATOR"])
def test_any_role_lists_alerts(api_as, role, make_alert):
    make_alert()
    resp = api_as(role).get(ALERTS_URL)
    assert resp.status_code == 200
    rows = resp.json().get("results") or resp.json()
    assert len(rows) >= 1


@pytest.mark.parametrize("role", ["ADMIN", "MANAGER", "CONTROLLER", "MAINTENANCE", "OPERATOR"])
def test_any_role_can_retrieve_single_alert(api_as, role, make_alert):
    a = make_alert()
    resp = api_as(role).get(f"{ALERTS_URL}/{a.pk}")
    assert resp.status_code == 200
    assert resp.json()["id"] == a.pk


def test_unauthenticated_list_401(api):
    assert api.get(ALERTS_URL).status_code == 401


# ---------------------------------------------------------------------------
# Declare (POST) — role gating in perform_create
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("role", ["ADMIN", "MANAGER", "CONTROLLER", "MAINTENANCE"])
def test_authorized_roles_can_declare(api_as, role, make_machine, make_category):
    from apps.alerts.models import Alert
    machine = make_machine()
    cat = make_category()
    payload = _declare_payload(machine, cat)
    # The role (CONTROLLER etc) is set on a user auto-created by api_as; we need
    # to know which User is "me" to compare reported_by.
    client = api_as(role)
    payload = _declare_payload(machine, cat)
    resp = client.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 201, resp.content
    # The create response uses AlertCreateSerializer which echoes the input fields
    # only (no id, no status, no reported_by). Verify state via the DB.
    body = resp.json()
    assert body["severity"] == "MAJOR"
    alert = Alert.objects.filter(machine=machine, title="Test alert").latest("created_at")
    assert alert.status == "OPEN"
    assert alert.reported_by_id == client.user.pk


def test_operator_cannot_declare(operator_client, make_machine, make_category):
    payload = _declare_payload(make_machine(), make_category())
    resp = operator_client.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 403
    assert "Rôle insuffisant" in resp.json()["detail"]


@pytest.mark.xfail(reason="bug #1: apps/alerts/views.py:55 on-duty gate is a no-op — fix will flip to xpass")
def test_offduty_controller_can_still_declare_documented_bug(
        offduty_controller, make_machine, make_category):
    """apps/alerts/views.py:55 has an `if not is_on_duty` block that ends with
    `pass` — the on-duty gate is currently a no-op. This test pins the current
    (buggy) behavior so a future fix flips it to xpass and forces the
    regression to be acknowledged."""
    from rest_framework.test import APIClient
    from rest_framework_simplejwt.tokens import RefreshToken

    payload = _declare_payload(make_machine(), make_category())
    c = APIClient()
    c.credentials(HTTP_AUTHORIZATION=f"Bearer {RefreshToken.for_user(offduty_controller).access_token}")
    resp = c.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 201  # <-- the bug: should be 403 once gate is fixed


def test_declare_without_machine_400(admin_client, make_category):
    payload = {
        "category": make_category().pk,
        "title": "x", "description": "", "severity": "MAJOR",
    }
    resp = admin_client.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 400


def test_declare_with_invalid_severity_400(admin_client, make_machine, make_category):
    payload = _declare_payload(make_machine(), make_category(), severity="STRANGE")
    resp = admin_client.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 400


def test_declare_sets_priority_score(admin_client, make_machine, make_category):
    from apps.alerts.models import Alert
    machine = make_machine()
    cat = make_category()
    payload = _declare_payload(machine, cat, severity="CRITICAL")
    resp = admin_client.post(ALERTS_URL, payload, format="json")
    assert resp.status_code == 201
    # priority_score is computed in Alert.save() (alerts/models.py). The create
    # serializer doesn't return priority_score, so verify via DB or retrieve.
    alert = Alert.objects.filter(machine=machine, severity="CRITICAL").latest("created_at")
    # severity weight 1000 + open bonus 1000 = 2000 for CRITICAL+OPEN
    assert alert.priority_score == 2000
    # And the retrieve endpoint exposes it too
    detail = admin_client.get(f"{ALERTS_URL}/{alert.pk}").json()
    assert detail["priority_score"] == 2000


# ---------------------------------------------------------------------------
# Filter / search / order
# ---------------------------------------------------------------------------
def test_filter_by_status(admin_client, make_alert):
    make_alert(status=AlertStatus.OPEN)
    make_alert(status=AlertStatus.RESOLVED)
    resp = admin_client.get(f"{ALERTS_URL}?status=RESOLVED")
    assert resp.status_code == 200
    rows = resp.json().get("results") or resp.json()
    assert all(r["status"] == "RESOLVED" for r in rows)


def test_filter_by_severity(admin_client, make_alert):
    make_alert(severity=Severity.CRITICAL)
    make_alert(severity=Severity.MINOR)
    resp = admin_client.get(f"{ALERTS_URL}?severity=CRITICAL")
    rows = resp.json().get("results") or resp.json()
    assert rows and all(r["severity"] == "CRITICAL" for r in rows)


# ---------------------------------------------------------------------------
# Delete
# ---------------------------------------------------------------------------
def test_admin_can_delete_alert(admin_client, make_alert):
    a = make_alert()
    assert admin_client.delete(f"{ALERTS_URL}/{a.pk}").status_code == 204
    assert not Alert.objects.filter(pk=a.pk).exists()


@pytest.mark.xfail(reason="bug #5: destroy action has no role gate — alerts/views.py:38 only IsAuthenticated")
@pytest.mark.parametrize("role", ["MANAGER", "CONTROLLER", "MAINTENANCE", "OPERATOR"])
def test_non_admin_delete_alert_should_be_forbidden_but_currently_succeeds(api_as, role, make_alert):
    a = make_alert()
    resp = api_as(role).delete(f"{ALERTS_URL}/{a.pk}")
    assert resp.status_code == 403
