# Generated by Django 5.1.3 on 2026-07-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(blank=True, default='DAY', max_length=20)),
                ('theoretical_production', models.PositiveIntegerField(default=0)),
                ('actual_production', models.PositiveIntegerField(default=0)),
                ('total_downtime_min', models.PositiveIntegerField(default=0)),
                ('shift_duration_min', models.PositiveIntegerField(default=1440)),
                ('availability_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('performance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('trs_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kwh_per_bottle', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('air_per_bottle', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('pet_per_bottle', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('reject_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oee_records', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Enregistrement OEE',
                'verbose_name_plural': 'Enregistrements OEE',
                'ordering': ['-date', 'machine__code'],
                'unique_together': {('date', 'shift', 'machine')},
            },
        ),
    ]
