# Generated by Django 5.1.3 on 2026-08-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeerecord',
            name='air_per_bottle',
        ),
        migrations.RemoveField(
            model_name='oeerecord',
            name='kwh_per_bottle',
        ),
        migrations.RemoveField(
            model_name='oeerecord',
            name='pet_per_bottle',
        ),
    ]
