# Generated by Django 5.1.3 on 2026-07-25 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Quotidienne'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle')], default='MONTHLY', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField()),
                ('status', models.CharField(choices=[('DUE', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée'), ('OVERDUE', 'En retard')], default='DUE', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_tasks', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_tasks', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Maintenance préventive',
                'verbose_name_plural': 'Maintenances préventives',
                'ordering': ['next_due'],
            },
        ),
    ]
