# Generated by Django 5.1.3 on 2026-08-19 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_seed_machine_equipment'),
        ('maintenance', '0002_intervention_verified_preventivemaintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Section de checklist',
                'verbose_name_plural': 'Sections de checklist',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de checklist',
                'verbose_name_plural': 'Modèles de checklist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.checklistsection')),
            ],
            options={
                'verbose_name': 'Élément de checklist',
                'verbose_name_plural': 'Éléments de checklist',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maintenance.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='MaintenanceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Matin (06h-14h)'), ('AFTERNOON', 'Après-midi (14h-22h)'), ('NIGHT', 'Nuit (22h-06h)')], max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_controls_confirmed', to=settings.AUTH_USER_MODEL)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_controls_started', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_controls', to='machines.auxiliaryequipment')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_controls', to='machines.machine')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='maintenance.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Contrôle préventif',
                'verbose_name_plural': 'Contrôles préventifs',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'À vérifier'), ('OK', 'Conforme'), ('PROBLEM', 'Problème')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='maintenance.maintenancecontrol')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='maintenance.checklistitem')),
            ],
            options={
                'verbose_name': 'Résultat de contrôle',
                'verbose_name_plural': 'Résultats de contrôle',
                'ordering': ['item__section__order', 'item__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancecontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('machine__isnull', False)), fields=('date', 'shift', 'template', 'machine'), name='uniq_control_per_machine_shift_day'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecontrol',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('date', 'shift', 'template', 'equipment'), name='uniq_control_per_equipment_shift_day'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenancecontrolresult',
            unique_together={('control', 'item')},
        ),
    ]
