# Generated by Django 5.1.3 on 2026-08-20 00:13

import apps.reclamation.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0007_seed_machine_equipment'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('client', models.CharField(max_length=150)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('product_reference', models.CharField(blank=True, default='', max_length=100)),
                ('production_at', models.DateTimeField(blank=True, help_text='Date/heure de production du produit concerné, si connue — utilisée pour identifier le personnel en poste.', null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('MAJOR', 'Majeur'), ('MINOR', 'Mineur')], default='MAJOR', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('INVESTIGATING', 'En investigation'), ('CORRECTED', 'Corrigée'), ('CLOSED', 'Clôturée')], default='OPEN', max_length=20)),
                ('resolved_personnel', models.JSONField(blank=True, default=dict)),
                ('resolution', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='machines.machine')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.reclamation.models._upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reclamation.reclamation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe de réclamation',
                'verbose_name_plural': 'Pièces jointes de réclamation',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
