# Generated by Django 5.1.3 on 2026-08-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_verified_at_package_verified_by'),
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='package.package'),
        ),
    ]
