# Generated by Django 5.1.3 on 2026-07-30 23:44

import apps.support.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('machines', '0002_machine_manufacturer_machine_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevée'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('AWAITING_SUPPLIER', 'En attente fournisseur'), ('DIAGNOSING', 'Diagnostic en cours'), ('SOLUTION_PROPOSED', 'Solution proposée'), ('INTERVENING', 'Intervention en cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé')], default='NEW', max_length=20)),
                ('production_line', models.CharField(blank=True, default='', max_length=120)),
                ('equipment_detail', models.CharField(blank=True, default='', max_length=200)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(blank=True, default='')),
                ('production_impacted', models.CharField(blank=True, default='', max_length=200)),
                ('downtime_start', models.DateTimeField(blank=True, null=True)),
                ('downtime_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='alerts.alert')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='machines.machine')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket SAV',
                'verbose_name_plural': 'Tickets SAV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(blank=True, default='')),
                ('probable_cause', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('repair_procedure', models.TextField(blank=True, default='')),
                ('spare_parts', models.TextField(blank=True, default='')),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Élevée'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], default='MEDIUM', max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='support.ticket')),
            ],
            options={
                'verbose_name': 'Solution fournisseur',
                'verbose_name_plural': 'Solutions fournisseur',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.support.models._upload_to)),
                ('category', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('PDF', 'PDF'), ('REPORT', 'Rapport'), ('SCREENSHOT', "Capture d'écran"), ('ALARM_LOG', 'Journal des alarmes'), ('TECHNICAL_FILE', 'Fichier technique')], default='PHOTO', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe de ticket',
                'verbose_name_plural': 'Pièces jointes de ticket',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_conforms', models.BooleanField(default=True)),
                ('restarted_at', models.DateTimeField(blank=True, null=True)),
                ('total_downtime_min', models.PositiveIntegerField(default=0)),
                ('intervention_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('parts_replaced', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='support.ticket')),
            ],
            options={
                'verbose_name': 'Clôture de ticket',
                'verbose_name_plural': 'Clôtures de ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire de ticket',
                'verbose_name_plural': 'Commentaires de ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('NEW', 'Nouveau'), ('AWAITING_SUPPLIER', 'En attente fournisseur'), ('DIAGNOSING', 'Diagnostic en cours'), ('SOLUTION_PROPOSED', 'Solution proposée'), ('INTERVENING', 'Intervention en cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('NEW', 'Nouveau'), ('AWAITING_SUPPLIER', 'En attente fournisseur'), ('DIAGNOSING', 'Diagnostic en cours'), ('SOLUTION_PROPOSED', 'Solution proposée'), ('INTERVENING', 'Intervention en cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé')], max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('ACCEPTED', 'Acceptée'), ('REFUSED', 'Refusée'), ('INFO_REQUESTED', 'Informations complémentaires demandées'), ('ONSITE_REQUESTED', 'Intervention sur site demandée'), ('VIDEOCALL_REQUESTED', 'Assistance visioconférence demandée')], default='', max_length=25)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='support.ticket')),
            ],
            options={
                'verbose_name': 'Historique de statut de ticket',
                'verbose_name_plural': 'Historiques de statut de ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='support_tic_status_363e60_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['machine', '-created_at'], name='support_tic_machine_8b928d_idx'),
        ),
    ]
