# Generated by Django 5.1.3 on 2026-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_assigned_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketclosure',
            name='machine_back_in_service',
            field=models.BooleanField(default=True),
        ),
    ]
