# Generated by Django 5.1.3 on 2026-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticketclosure_machine_back_in_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='request_type',
            field=models.CharField(blank=True, choices=[('QUESTION', 'Question'), ('TEST_REQUEST', 'Essai complémentaire demandé'), ('PHOTO_REQUEST', 'Photos supplémentaires demandées')], default='', max_length=20),
        ),
    ]
