# Generated by Django 5.1.3 on 2026-08-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticketcomment_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.suppliersolution'),
        ),
    ]
