# Generated by Django 5.1.3 on 2026-07-25 19:24

import apps.quality.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('clause', models.CharField(blank=True, default='', max_length=40)),
                ('file', models.FileField(upload_to=apps.quality.models._upload_to)),
                ('version', models.CharField(blank=True, default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY', 'Prêt'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Document d'audit",
                'verbose_name_plural': "Documents d'audit",
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('source', models.CharField(choices=[('INTERNAL', 'Interne'), ('CUSTOMER', 'Client'), ('AUDIT', 'Audit'), ('ALERT', 'Alerte')], default='INTERNAL', max_length=20)),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(choices=[('CRITICAL', 'Critique'), ('MAJOR', 'Majeur'), ('MINOR', 'Mineur')], default='MAJOR', max_length=20)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('INVESTIGATING', 'En investigation'), ('CORRECTED', 'Corrigée'), ('CLOSED', 'Clôturée')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='alerts.alert')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='machines.machine')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-opened_at'],
            },
        ),
    ]
