# Generated by Django 5.1.3 on 2026-07-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('target_bph', models.PositiveIntegerField(default=0)),
                ('actual_bph', models.PositiveIntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Plan de production',
                'verbose_name_plural': 'Plans de production',
                'ordering': ['-date', 'machine__code'],
                'unique_together': {('date', 'machine', 'product')},
            },
        ),
    ]
