# Generated by Django 5.1.3 on 2026-08-20 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('machines', '0007_seed_machine_equipment'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('color_formulation', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField()),
                ('time_per_bottle_sec', models.DecimalField(decimal_places=3, max_digits=8)),
                ('mold_change_min', models.PositiveIntegerField(default=0, help_text='Temps de changement de moule requis avant cette commande, si le moule diffère de la précédente')),
                ('priority', models.IntegerField(default=100)),
                ('requested_start', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', "En file d'attente"), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], default='QUEUED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_orders', to='catalog.bottlecharacteristic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_orders_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_orders', to='machines.machine')),
                ('mold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_orders', to='machines.mold')),
            ],
            options={
                'verbose_name': 'Commande de planning',
                'verbose_name_plural': 'Commandes de planning',
                'ordering': ['machine', 'priority', 'id'],
            },
        ),
    ]
