# Generated by Django 5.1.3 on 2026-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningorder',
            options={'ordering': ['machine', 'requested_start', 'id'], 'verbose_name': 'Commande de planning', 'verbose_name_plural': 'Commandes de planning'},
        ),
        migrations.RemoveField(
            model_name='planningorder',
            name='priority',
        ),
    ]
