# Generated by Django 5.1.3 on 2026-08-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_planningorder_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionPlan',
        ),
    ]
