# Generated by Django 5.1.3 on 2026-08-20 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0007_seed_machine_equipment'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('bottle_count', models.PositiveIntegerField()),
                ('raw_material_reference_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('color_reference_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=150)),
                ('production_started_at', models.DateTimeField()),
                ('production_finished_at', models.DateTimeField(blank=True, null=True)),
                ('personnel_snapshot', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_as_color', to='stock.stockitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='machines.machine')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_as_raw_material', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Sac (package)',
                'verbose_name_plural': 'Sacs (package)',
                'ordering': ['-production_started_at'],
            },
        ),
    ]
