# Generated by Django 5.1.3 on 2026-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_bottle_package_colorant_consumed_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='shipped_to',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
