# Generated by Django 5.1.3 on 2026-08-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package_shipped_at_package_shipped_to'),
        ('planning', '0003_alter_planningorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='planning_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='planning.planningorder'),
        ),
    ]
