# Generated by Django 5.1.3 on 2026-07-26 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_activ_user_id_60d287_idx'), models.Index(fields=['action'], name='audit_activ_action_259cfa_idx')],
            },
        ),
    ]
