# Generated by Django 5.1.3 on 2026-08-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('raw_material_qty_g', models.DecimalField(decimal_places=3, help_text='Matière première par bouteille (g)', max_digits=10)),
                ('colorant_qty_g', models.DecimalField(decimal_places=3, default=0, help_text='Colorant par bouteille (g)', max_digits=10)),
                ('bouchant_type', models.CharField(choices=[('HDPE', 'HDPE'), ('LDPE', 'LDPE'), ('COLORANT', 'Colorant')], default='HDPE', max_length=20)),
                ('bouchant_raw_material_qty_g', models.DecimalField(decimal_places=3, default=0, help_text='Matière première du bouchon (g)', max_digits=10)),
                ('bouchant_colorant_qty_g', models.DecimalField(decimal_places=3, default=0, help_text='Colorant du bouchon (g)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colorant', models.ForeignKey(blank=True, limit_choices_to={'type': 'COLORANT'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bottle_colorants', to='stock.stockitem')),
                ('raw_material', models.ForeignKey(limit_choices_to={'type': 'RAW_MATERIAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='bottle_bodies', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Caractéristique bouteille',
                'verbose_name_plural': 'Caractéristiques bouteille',
                'ordering': ['category'],
            },
        ),
    ]
