# Generated by Django 5.1.3 on 2026-08-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('BOTTLE_RAW', 'Matière première bouteille'), ('BOTTLE_COLORANT', 'Colorant bouteille'), ('CAP_RAW', 'Matière première bouchon'), ('CAP_COLORANT', 'Colorant bouchon')], max_length=20)),
                ('qty_per_unit_g', models.DecimalField(decimal_places=3, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.bottlecharacteristic')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Composant de recette',
                'verbose_name_plural': 'Composants de recette',
                'ordering': ['recipe', 'component_type'],
                'unique_together': {('recipe', 'component_type')},
            },
        ),
    ]
