# Generated by Django 5.1.3 on 2026-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_backfill_recipe_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecharacteristic',
            name='time_per_bottle_sec',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
